### PR TITLE
Warning: this package can cause kernel panic for 10.15.6 /10.15.7 on some hardware.

### PR DESCRIPTION
**Pull request by vikas0380**

### CODE REVIEW

**Comment by vikas0380** [comment]
@chris1111 just want to aware people about the kernel panic, till the issue is fixed.

**Comment by chris1111** [comment]
I don't have issue on 10.15.6 , 10.15.7 GeForce 210 and Intel HD 3000

**Comment by vikas0380** [comment]
Its not only me, please take a look.

https://www.tonymacx86.com/threads/full-acceleration-for-intel-hd-3000-and-older-nvidia-graphics-in-macos-catalina.290488/page-16

**Comment by chris1111** [comment]
ok its merge

**Comment by chris1111** [comment]
See I fix issue on some hardware my test on 10.15.6 Then Update to 10.15.7 
I will update Legacy Video patch verry soon tonight 😁
Screen Shot 1
Screen Shot 2
Screen Shot 3

**Comment by vikas0380** [comment]
@chris1111 thanks for the update, not sure about others, but mine is not working. Getting AMFI : Denying core dump for pid < incremental numbers >
![Uploading 96491270...]

**Comment by chris1111** [comment]
I don't have this issue since 10.15.4 Google the issue and you find answer
anyway you do not say which machine and which hardware you use, with which Clover version

**Comment by iamRyanChia** [comment]
Hello, I installed it on macos 10.15.7, but when it needs to be restarted, the computer has been loading and cannot be shut down and restarted. Hope you can help me, thanks.

The computer motherboard model is Gigabyte B85m d2v, the CPU is i5-4590, the core graphics card is HD 4600, and the discrete graphics card is GT 210

**Comment by iamRyanChia** [comment]
When I forced shutdown and restart, the error message of the friend above appeared, I have closed the system SIP

**Comment by chris1111** [comment]
> Hello, I installed it on macos 10.15.7, but when it needs to be restarted, the computer has been loading and cannot be shut down and restarted. Hope you can help me, thanks.
> 
> The computer motherboard model is Gigabyte B85m d2v, the CPU is i5-4590, the core graphics card is HD 4600, and the discrete graphics card is GT 210

The restart shutdown issue is not relate to legacy video patch
 Please don't post this kind of issue here

**Pull request merged**
